// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using b221210566_2_.Data;

#nullable disable

namespace b221210566_2_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("b221210566_2_.Models.SalonOperation+Appointments", b =>
                {
                    b.Property<int>("AppNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppNo"));

                    b.Property<int>("AppDate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AppTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Coast")
                        .HasColumnType("real");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppNo");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("b221210566_2_.Models.SalonOperation+Scudle", b =>
                {
                    b.Property<int>("AppNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppNo"));

                    b.Property<int>("AppDate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AppTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.HasKey("AppNo");

                    b.HasIndex("ManagerId");

                    b.ToTable("Scudle");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+HCare", b =>
                {
                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SupervisorId");

                    b.ToTable("HCare");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+HCut", b =>
                {
                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SupervisorId");

                    b.ToTable("HCut");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+HDye", b =>
                {
                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("supervisorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("supervisorId");

                    b.ToTable("HDye");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+Manikur", b =>
                {
                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Manikur");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+Pedikur", b =>
                {
                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Pedikur");
                });

            modelBuilder.Entity("b221210566_2_.Models.Team", b =>
                {
                    b.ToTable("Teams");
                });

            modelBuilder.Entity("b221210566_2_.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.ToTable("users");
                });

            modelBuilder.Entity("b221210566_2_.Models.CustomerData", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.User");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CEmail");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CName");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CPhone");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CPassword");

                    b.ToTable("CustomerData");
                });

            modelBuilder.Entity("b221210566_2_.Models.EmployeeExample", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.User");

                    b.Property<string>("DirektManagerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GeneralManagerId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DirektManagerId");

                    b.HasIndex("GeneralManagerId");

                    b.ToTable("EmployeeExample");
                });

            modelBuilder.Entity("b221210566_2_.Models.FinancialManager", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.User");

                    b.Property<string>("DirectManagerId")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DirectManagerId");

                    b.ToTable("FinancialManager");
                });

            modelBuilder.Entity("b221210566_2_.Models.GeneralManager", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.User");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("GeneralManager");
                });

            modelBuilder.Entity("b221210566_2_.Models.SalonManager", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.User");

                    b.Property<string>("DirectManagerId")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DirectManagerId");

                    b.ToTable("SalonManager");
                });

            modelBuilder.Entity("b221210566_2_.Models.SupervisorExample", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.User");

                    b.Property<string>("DirekManagerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GeneralManagerId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DirekManagerId");

                    b.HasIndex("GeneralManagerId");

                    b.ToTable("SupervisorExample");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCareEmp", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.EmployeeExample");

                    b.Property<string>("HCareSvId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("HCareSvId");

                    b.ToTable("HCareEmp");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCutEmp", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.EmployeeExample");

                    b.Property<string>("HCareSvId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HCutSvId")
                        .HasColumnType("text");

                    b.HasIndex("HCareSvId");

                    b.HasIndex("HCutSvId");

                    b.ToTable("HCutEmp");
                });

            modelBuilder.Entity("b221210566_2_.Models.HDyeEmp", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.EmployeeExample");

                    b.Property<string>("HDyeSvId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("HDyeSvId");

                    b.ToTable("HDyeEmp");
                });

            modelBuilder.Entity("b221210566_2_.Models.ManikurE", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.EmployeeExample");

                    b.Property<string>("ManikurSId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ManikurSId");

                    b.ToTable("ManikurE");
                });

            modelBuilder.Entity("b221210566_2_.Models.PadikurE", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.EmployeeExample");

                    b.Property<string>("PadikurSId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("PadikurSId");

                    b.ToTable("PadikurE");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCareSv", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.SupervisorExample");

                    b.ToTable("HCareSv");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCutSv", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.SupervisorExample");

                    b.ToTable("HCutSv");
                });

            modelBuilder.Entity("b221210566_2_.Models.HDyeSv", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.SupervisorExample");

                    b.ToTable("HDyeSv");
                });

            modelBuilder.Entity("b221210566_2_.Models.ManikurS", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.SupervisorExample");

                    b.ToTable("ManikurS");
                });

            modelBuilder.Entity("b221210566_2_.Models.PadikurS", b =>
                {
                    b.HasBaseType("b221210566_2_.Models.SupervisorExample");

                    b.ToTable("PadikurS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.SalonOperation+Appointments", b =>
                {
                    b.HasOne("b221210566_2_.Models.SupervisorExample", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("b221210566_2_.Models.SalonOperation+Scudle", b =>
                {
                    b.HasOne("b221210566_2_.Models.SalonManager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+HCare", b =>
                {
                    b.HasOne("b221210566_2_.Models.HCareSv", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+HCut", b =>
                {
                    b.HasOne("b221210566_2_.Models.HCutSv", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+HDye", b =>
                {
                    b.HasOne("b221210566_2_.Models.HDyeSv", "supervisor")
                        .WithMany()
                        .HasForeignKey("supervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+Manikur", b =>
                {
                    b.HasOne("b221210566_2_.Models.ManikurS", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("b221210566_2_.Models.Servises+Pedikur", b =>
                {
                    b.HasOne("b221210566_2_.Models.PadikurS", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("b221210566_2_.Models.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.CustomerData", b =>
                {
                    b.HasOne("b221210566_2_.Models.User", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.CustomerData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.EmployeeExample", b =>
                {
                    b.HasOne("b221210566_2_.Models.SalonManager", "DirektManager")
                        .WithMany("Employees")
                        .HasForeignKey("DirektManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("b221210566_2_.Models.GeneralManager", null)
                        .WithMany("SalonEmployees")
                        .HasForeignKey("GeneralManagerId");

                    b.HasOne("b221210566_2_.Models.User", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.EmployeeExample", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirektManager");
                });

            modelBuilder.Entity("b221210566_2_.Models.FinancialManager", b =>
                {
                    b.HasOne("b221210566_2_.Models.GeneralManager", "DirectManager")
                        .WithMany("FinancialManagers")
                        .HasForeignKey("DirectManagerId");

                    b.HasOne("b221210566_2_.Models.User", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.FinancialManager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectManager");
                });

            modelBuilder.Entity("b221210566_2_.Models.GeneralManager", b =>
                {
                    b.HasOne("b221210566_2_.Models.User", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.GeneralManager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.SalonManager", b =>
                {
                    b.HasOne("b221210566_2_.Models.GeneralManager", "DirectManager")
                        .WithMany("salonManagers")
                        .HasForeignKey("DirectManagerId");

                    b.HasOne("b221210566_2_.Models.User", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.SalonManager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectManager");
                });

            modelBuilder.Entity("b221210566_2_.Models.SupervisorExample", b =>
                {
                    b.HasOne("b221210566_2_.Models.SalonManager", "DirekManager")
                        .WithMany("Supervisors")
                        .HasForeignKey("DirekManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("b221210566_2_.Models.GeneralManager", null)
                        .WithMany("Supervisors")
                        .HasForeignKey("GeneralManagerId");

                    b.HasOne("b221210566_2_.Models.User", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.SupervisorExample", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirekManager");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCareEmp", b =>
                {
                    b.HasOne("b221210566_2_.Models.HCareSv", "HCareSv")
                        .WithMany("CareEmps")
                        .HasForeignKey("HCareSvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("b221210566_2_.Models.EmployeeExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.HCareEmp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HCareSv");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCutEmp", b =>
                {
                    b.HasOne("b221210566_2_.Models.HCareSv", "HCareSv")
                        .WithMany()
                        .HasForeignKey("HCareSvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("b221210566_2_.Models.HCutSv", null)
                        .WithMany("CutEmps")
                        .HasForeignKey("HCutSvId");

                    b.HasOne("b221210566_2_.Models.EmployeeExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.HCutEmp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HCareSv");
                });

            modelBuilder.Entity("b221210566_2_.Models.HDyeEmp", b =>
                {
                    b.HasOne("b221210566_2_.Models.HDyeSv", "HDyeSv")
                        .WithMany("DyeEmps")
                        .HasForeignKey("HDyeSvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("b221210566_2_.Models.EmployeeExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.HDyeEmp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HDyeSv");
                });

            modelBuilder.Entity("b221210566_2_.Models.ManikurE", b =>
                {
                    b.HasOne("b221210566_2_.Models.EmployeeExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.ManikurE", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("b221210566_2_.Models.ManikurS", "ManikurS")
                        .WithMany("ManuEmps")
                        .HasForeignKey("ManikurSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManikurS");
                });

            modelBuilder.Entity("b221210566_2_.Models.PadikurE", b =>
                {
                    b.HasOne("b221210566_2_.Models.EmployeeExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.PadikurE", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("b221210566_2_.Models.PadikurS", "PadikurS")
                        .WithMany("PaduEmps")
                        .HasForeignKey("PadikurSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PadikurS");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCareSv", b =>
                {
                    b.HasOne("b221210566_2_.Models.SupervisorExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.HCareSv", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.HCutSv", b =>
                {
                    b.HasOne("b221210566_2_.Models.SupervisorExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.HCutSv", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.HDyeSv", b =>
                {
                    b.HasOne("b221210566_2_.Models.SupervisorExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.HDyeSv", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.ManikurS", b =>
                {
                    b.HasOne("b221210566_2_.Models.SupervisorExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.ManikurS", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.PadikurS", b =>
                {
                    b.HasOne("b221210566_2_.Models.SupervisorExample", null)
                        .WithOne()
                        .HasForeignKey("b221210566_2_.Models.PadikurS", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("b221210566_2_.Models.GeneralManager", b =>
                {
                    b.Navigation("FinancialManagers");

                    b.Navigation("SalonEmployees");

                    b.Navigation("Supervisors");

                    b.Navigation("salonManagers");
                });

            modelBuilder.Entity("b221210566_2_.Models.SalonManager", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCareSv", b =>
                {
                    b.Navigation("CareEmps");
                });

            modelBuilder.Entity("b221210566_2_.Models.HCutSv", b =>
                {
                    b.Navigation("CutEmps");
                });

            modelBuilder.Entity("b221210566_2_.Models.HDyeSv", b =>
                {
                    b.Navigation("DyeEmps");
                });

            modelBuilder.Entity("b221210566_2_.Models.ManikurS", b =>
                {
                    b.Navigation("ManuEmps");
                });

            modelBuilder.Entity("b221210566_2_.Models.PadikurS", b =>
                {
                    b.Navigation("PaduEmps");
                });
#pragma warning restore 612, 618
        }
    }
}
